language: node_js
node_js:
  - 12
before_install:
  - npm update
install:
  - npm install -g firebase-tools
  - npm --prefix functions install
before_script:
  - openssl aes-256-cbc -K $encrypted_d45aa3630c30_key -iv $encrypted_d45aa3630c30_iv
    -in permissions.json.enc -out ./functions/permissions.json -d
  - export GOOGLE_APPLICATION_CREDENTIALS=./permissions.json
script:
  - npm --prefix functions test
before_deploy:
  - env -u $GOOGLE_APPLICATION_CREDENTIALS
deploy:
  provider: firebase
  token:
    secure: luLg9jgJ2R6dqXmi07S+tr2z4DoLQFbbIiXtFbrjMwDAuAg6l4H0JTNKhZ67XAW6P660Pep7bB5pb7Ek9iCc6XF+f1QCrLwLSYtAmxLGHp/kB+vD2dmsaQurHbJtQnLL/OVnudGMezhv71dG1fj2u7vvva1jk2T8mptR1+Dtxqpy3Cjv4KK3qDdsibySR+0vZfYi042LRKJYAfxmd9Uyzt/8f6R+SywFCD5sgWNzFTPXWClKFmNYcs+xSSwqOeWR5QFxnhUuG+hs9PbrxFmcGvcjKsQAAcglH6qC2dsaHzidguTdyk7CwLdB8DdLdFQx2457RTMyWcaqqGhQ4KC5LZrmPk92fPX2EAk2nDhsCS2dcAyn/GtU/CRAshE8J/grv55KzrcenxLBI20UegcdQQdRJ+yEhBdjuFH+AIOJf04lCk18ky+MI2ZhOwRX4H9fq1boCpWy3Hz3M6FEzwmMgF+0nVNAFLeyve16opWuAZwifQH+D/5nKL87ZC56jJ1R2TzVhZtfk1sp8507tPo1RlTIgt0RyN+YdHLB+jS72LRJiPo3g1e6rXX6rR2q/4lVC6ISwE4sJyvDliM6Nzve4/LNaqGw+UtPXc6tUwzdz6Q8oGd2t5B5GXbRU2cWK7dyjES9wheqM1P179lDAm4ZX/34/hvuicdHzbDd/wWX/5g=
  on:
    branch: main
